### ISSUE TITLE
[EPIC] C# support

### ISSUE THREAD

**Issue by mscottford** [corgibytes/freshli#11]
Build out C# language support. Initially targeting the support for C# that existed in `freshli-lib` (analyzing `*.csproj` files).

- [x] corgibytes/freshli-cli#557
- [x] corgibytes/freshli-agent-dotnet#1
- [ ] corgibytes/freshli-agent-dotnet#7
- [ ] corgibytes/freshli-agent-dotnet#4
- [ ] corgibytes/freshli-cli#605
- [ ] corgibytes/freshli-agent-dotnet#9
- [ ] corgibytes/freshli-agent-dotnet#10
