### ISSUE TITLE
[EPIC] Perl support

### ISSUE THREAD

**Issue by mscottford** [corgibytes/freshli#13]
Build out Perl language support. Initially targeting the support for Perl that existed in `freshli-lib` (analyzing `cpanfile`)

- [ ] Create GitHub repository for `freshli-agent-perl`

(The following issues should be moved to the repository that's created above once it exists.)
- [ ] Add skeleton command line application
- [ ] Implement `detect-manifest`
- [ ] Implement `process-manifest`
- [ ] Implement `validating-repositories`
- [ ] Implement `retrieve-release-history`
- [ ] Implement `validating-package-urls`
- [ ] Validate against `freshli agents verify` command

(The following issue should belong to this project)
- [ ] Add `freshli-agent-perl` to production docker container image
