### ISSUE TITLE
[EPIC] Ruby support

### ISSUE THREAD

**Issue by mscottford** [corgibytes/freshli#16]
Build out Ruby language support. Initially targeting the support for Ruby that existed in `freshli-lib` (analyzing `Gemfile.lock`)

- [ ] corgibytes/freshli-cli#254

(The following issues should be moved to the repository that's created above once it exists.)
- [ ] Add skeleton command line application
- [ ] Implement `detect-manifest`
- [ ] Implement `process-manifest`
- [ ] Implement `validating-repositories`
- [ ] Implement `retrieve-release-history`
- [ ] Implement `validating-package-urls`
- [ ] Validate against `freshli agents verify` command

(The following issue should belong to this project)
- [ ] Add `freshli-agent-ruby` to production docker container image
