### ISSUE TITLE
Adopt Contributor Covenant across all repositories

### ISSUE THREAD

**Issue by mscottford** [corgibytes/freshli#20]
Use the latest version of the [Contributor Covenenat](https://www.contributor-covenant.org/).

- [x] corgibytes/freshli#21
- [x] corgibytes/freshli-cli#619
- [x] corgibytes/freshli-agent-dotnet#16
- [x] corgibytes/freshli-agent-java#115
- [x] corgibytes/freshli-agent-python#8
- [x] corgibytes/freshli-agent-go#9
- [x] corgibytes/dependency-history-maven#71
- [x] corgibytes/freshli-commons#4

**Comment by mscottford** [comment]
This is all done.
