### ISSUE TITLE
Require authentication

### ISSUE THREAD

**Issue by mscottford** [corgibytes/freshli#31]
- [x] corgibytes/freshli-cli#698
- [ ] corgibytes/freshli-cli#647
- [ ] corgibytes/freshli-cli#648
- [ ] corgibytes/freshli-cli#649
