### ISSUE TITLE
Send analysis data to api.freshli.io associated with an authorized user's project

### ISSUE THREAD

**Issue by mscottford** [corgibytes/freshli#32]
* [ ] corgibytes/freshli-cli#650
* [ ] corgibytes/freshli#31
* [ ] corgibytes/freshli-cli#644
* [ ] corgibytes/freshli-cli#645
* [ ] corgibytes/freshli-cli#646
