### ISSUE TITLE
[EPIC] Versioned language agents

### ISSUE THREAD

**Issue by mscottford** [corgibytes/freshli#7]
It can be difficult to determine if specific changes are included in the executable that someone has installed. To help with that difficulty, we need to add versions.

- [ ] corgibytes/freshli-cli#348
- [ ] corgibytes/freshli-agent-java#36
- [ ] corgibytes/freshli-agent-java#37
- [ ] corgibytes/freshli-cli#566
